/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        // Clinical Light — sourced from Stitch design system
        "surface":                   "#faf8ff",
        "surface-dim":               "#d9d9e4",
        "surface-bright":            "#faf8ff",
        "surface-container-lowest":  "#ffffff",
        "surface-container-low":     "#f3f3fd",
        "surface-container":         "#ededf8",
        "surface-container-high":    "#e7e7f2",
        "surface-container-highest": "#e1e2ec",
        "surface-variant":           "#e1e2ec",
        "on-surface":                "#191b23",
        "on-surface-variant":        "#434654",
        "outline":                   "#737685",
        "outline-variant":           "#c3c6d6",
        "surface-tint":              "#0c56d0",
        "primary":                   "#17A077",  // Lumina green (charts, icons, progress)
        "on-primary":                "#ffffff",
        "primary-container":         "#0D9460",  // Lumina deep green (CTAs, active nav)
        "on-primary-container":      "#E0F5EE",
        "primary-fixed":             "#C8EDE4",
        "primary-fixed-dim":         "#90D4C0",
        "inverse-primary":           "#65C8AE",
        "on-primary-fixed":          "#022B1D",
        "on-primary-fixed-variant":  "#0E7056",
        "secondary":                 "#0D9460",  // Lumina green (status, sync, EHR)
        "on-secondary":              "#ffffff",
        "secondary-container":       "#C8EDE4",
        "on-secondary-container":    "#0D9460",
        "secondary-fixed":           "#E0F5EE",
        "secondary-fixed-dim":       "#A8DDD0",
        "on-secondary-fixed":        "#032E1E",
        "on-secondary-fixed-variant":"#0A6B47",
        "tertiary":                  "#7b2600",
        "on-tertiary":               "#ffffff",
        "tertiary-container":        "#a33500",
        "on-tertiary-container":     "#ffc6b2",
        "tertiary-fixed":            "#ffdbcf",
        "tertiary-fixed-dim":        "#ffb59b",
        "on-tertiary-fixed":         "#380d00",
        "on-tertiary-fixed-variant": "#812800",
        "error":                     "#ba1a1a",
        "on-error":                  "#ffffff",
        "error-container":           "#ffdad6",
        "on-error-container":        "#93000a",
        "background":                "#faf8ff",
        "on-background":             "#191b23",
        "inverse-surface":           "#2e3038",
        "inverse-on-surface":        "#f0f0fb",
      },
      spacing: {
        "xs":             "4px",
        "sm":             "12px",
        "md":             "24px",
        "lg":             "40px",
        "xl":             "64px",
        "base":           "8px",
        "gutter":         "24px",
        "margin-desktop": "32px",
        "margin-mobile":  "16px",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "400" }],
        "headline-md": ["28px", { lineHeight: "36px", fontWeight: "400" }],
        "headline-sm": ["24px", { lineHeight: "32px", fontWeight: "400" }],
        "title-lg":    ["22px", { lineHeight: "28px", fontWeight: "400" }],
        "title-md":    ["16px", { lineHeight: "24px", fontWeight: "500", letterSpacing: "0.015em" }],
        "title-sm":    ["14px", { lineHeight: "20px", fontWeight: "500", letterSpacing: "0.01em" }],
        "label-lg":    ["14px", { lineHeight: "20px", fontWeight: "500", letterSpacing: "0.01em" }],
        "label-md":    ["12px", { lineHeight: "16px", fontWeight: "500", letterSpacing: "0.05em" }],
        "label-sm":    ["11px", { lineHeight: "16px", fontWeight: "500", letterSpacing: "0.05em" }],
        "body-lg":     ["16px", { lineHeight: "24px" }],
        "body-md":     ["14px", { lineHeight: "20px", letterSpacing: "0.025em" }],
        "body-sm":     ["12px", { lineHeight: "16px", letterSpacing: "0.04em" }],
      },
      borderRadius: {
        sm:      "2px",
        DEFAULT: "4px",
        md:      "4px",
        lg:      "8px",
        xl:      "12px",
        full:    "9999px",
      },
    },
  },
  plugins: [],
};
