#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# seal-secrets.sh — Generate sealed secret values for a DiagDesk branch cluster
#
# Run this script ON the branch server AFTER the Sealed Secrets controller
# and diagdesk-branch chart are installed.
#
# Usage:
#   ./seal-secrets.sh [NAMESPACE]
#
# Output:
#   values-production.yaml — contains sealed (encrypted) values ready for Helm.
#   Commit this file to git; it is safe to store publicly.
#
# Re-deploy after sealing:
#   helm upgrade diagdesk-branch ./diagdesk-branch \
#     -f values.yaml -f values-branch.yaml -f values-production.yaml
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

NAMESPACE="${1:-diagdesk-branch}"
SECRET_NAME="diagdesk-app-secrets"
OUTPUT="values-production.yaml"

log()  { echo "[seal] $*"; }
fail() { echo "[seal] ERROR: $*" >&2; exit 1; }

# Require kubeseal
command -v kubeseal &>/dev/null || fail "kubeseal not installed. Download from: https://github.com/bitnami-labs/sealed-secrets/releases"

# Check connectivity to sealed-secrets controller
kubeseal --fetch-cert --controller-namespace kube-system &>/dev/null \
  || fail "Cannot reach sealed-secrets controller. Is it installed and running?"

seal_value() {
  local value="$1"
  echo -n "$value" | kubeseal --raw \
    --namespace "$NAMESPACE" \
    --name "$SECRET_NAME" \
    --scope namespace-wide
}

log "Sealing secrets for namespace=${NAMESPACE}, secret=${SECRET_NAME}"
log "Enter values below (input is hidden):"
echo ""

read -r -s -p "  DB_PASSWORD (PostgreSQL app user password): "       DB_PASS;           echo
read -r -s -p "  SUPABASE_SERVICE_ROLE_KEY (from Supabase dashboard): " SUPA_KEY;      echo
read -r -s -p "  MSG91_AUTH_KEY (from MSG91 dashboard): "            MSG91_KEY;         echo
read -r -s -p "  INTERNAL_SERVICE_TOKEN (Keycloak service account JWT, leave blank to skip): " SVC_TOKEN; echo
read -r -s -p "  KEYCLOAK_ADMIN_PASSWORD (Keycloak admin password, leave blank to skip): " KC_PASS;    echo
echo ""

log "Sealing values..."

SEALED_DB_PASS=$(seal_value "$DB_PASS")
SEALED_SUPA_KEY=$(seal_value "$SUPA_KEY")
SEALED_MSG91=$(seal_value "$MSG91_KEY")
SEALED_SVC_TOKEN=$([ -n "$SVC_TOKEN" ] && seal_value "$SVC_TOKEN" || echo "")
SEALED_KC_PASS=$([ -n "$KC_PASS" ]    && seal_value "$KC_PASS"    || echo "")

cat > "$OUTPUT" << YAML
# ── Sealed secrets for namespace: ${NAMESPACE} ──────────────────────────────
# Generated by seal-secrets.sh — safe to commit to git.
# Encrypted with this cluster's Sealed Secrets controller public key.
# Re-run seal-secrets.sh if the controller is re-installed (new key pair).
sealedSecrets:
  enabled: true
  dbPassword: "${SEALED_DB_PASS}"
  supabaseServiceRoleKey: "${SEALED_SUPA_KEY}"
  msg91AuthKey: "${SEALED_MSG91}"
  internalServiceToken: "${SEALED_SVC_TOKEN}"
  keycloakAdminPassword: "${SEALED_KC_PASS}"
YAML

log ""
log "Sealed values written to: $OUTPUT"
log ""
log "Re-deploy with:"
log "  helm upgrade diagdesk-branch ./diagdesk-branch \\"
log "    -f values.yaml -f values-branch.yaml -f ${OUTPUT}"
