#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# seal-central-secrets.sh — Generate sealed secret values for the DiagDesk
# central cloud deployment (mis-analytics, audit-consent, b2b-billing).
#
# Usage:
#   ./seal-central-secrets.sh [NAMESPACE]
#
# Output:
#   values-central-production.yaml — ready for helm upgrade -f
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

NAMESPACE="${1:-diagdesk-central}"
SECRET_NAME="diagdesk-central-secrets"
OUTPUT="values-central-production.yaml"

log()  { echo "[seal] $*"; }
fail() { echo "[seal] ERROR: $*" >&2; exit 1; }

command -v kubeseal &>/dev/null || fail "kubeseal not installed. Download from: https://github.com/bitnami-labs/sealed-secrets/releases"
kubeseal --fetch-cert --controller-namespace kube-system &>/dev/null \
  || fail "Cannot reach sealed-secrets controller. Is it installed and running?"

seal_value() {
  echo -n "$1" | kubeseal --raw \
    --namespace "$NAMESPACE" \
    --name "$SECRET_NAME" \
    --scope namespace-wide
}

log "Sealing central secrets for namespace=${NAMESPACE}"
log "Enter values below (input is hidden):"
echo ""

read -r -s -p "  DB_USER (Supabase user, e.g. postgres.projectref): "    DB_USER;      echo
read -r -s -p "  DB_PASSWORD (Supabase project password): "               DB_PASS;      echo
read -r -s -p "  KAFKA_SASL_USERNAME (leave blank if no Kafka): "         KAFKA_USER;   echo
read -r -s -p "  KAFKA_SASL_PASSWORD (leave blank if no Kafka): "         KAFKA_PASS;   echo
read -r -s -p "  KEYCLOAK_ADMIN_PASSWORD (leave blank to skip): "         KC_PASS;      echo
echo ""

log "Sealing values..."

SEALED_DB_USER=$(seal_value "$DB_USER")
SEALED_DB_PASS=$(seal_value "$DB_PASS")
SEALED_KAFKA_USER=$([ -n "$KAFKA_USER" ] && seal_value "$KAFKA_USER" || echo "")
SEALED_KAFKA_PASS=$([ -n "$KAFKA_PASS" ] && seal_value "$KAFKA_PASS" || echo "")
SEALED_KC_PASS=$([ -n "$KC_PASS" ]    && seal_value "$KC_PASS"    || echo "")

cat > "$OUTPUT" << YAML
# ── Sealed secrets for namespace: ${NAMESPACE} ──────────────────────────────
# Generated by seal-central-secrets.sh — safe to commit to git.
# Encrypted with this cluster's Sealed Secrets controller public key.
sealedSecrets:
  enabled: true
  dbUser: "${SEALED_DB_USER}"
  dbPassword: "${SEALED_DB_PASS}"
  kafkaSaslUsername: "${SEALED_KAFKA_USER}"
  kafkaSaslPassword: "${SEALED_KAFKA_PASS}"
  keycloakAdminPassword: "${SEALED_KC_PASS}"
YAML

log ""
log "Sealed values written to: $OUTPUT"
log ""
log "Re-deploy with:"
log "  helm upgrade diagdesk-central ./diagdesk-central \\"
log "    -f values.yaml -f ${OUTPUT}"
